package local_constants

const (
	PENDING_STATUS  = "pending"
	COMPLETE_STATUS = "complete"
	JOB_STARTING    = "STARTING"
	JOB_FAILED      = "FAILED"
	JOB_DOWNLOADING = "DOWNLOADING"
	JOB_FRAGMENTING = "FRAGMENTING"
	JOB_ENCODING    = "ENCODING"
	JOB_UPLOADING   = "UPLOADING"
	JOB_FINISHING   = "FINISHING"
	JOB_COMPLETED   = "COMPLETED"
)
