package local_constants

const (
	TEST_TOKEN                             = "test"
	LOCAL_STORAGE_PATH_ENV                 = "LOCAL_STORAGE_PATH"
	CONCURRENCY_ENV                        = "CONCURRENCY_UPLOADS"
	CONCURRENCY_WORKERS_ENV                = "CONCURRENCY_WORKERS"
	RABBIT_MQ_DLX_ENV                      = "RABBIT_MQ_DLX"
	RABBIT_MQ_DEFAULT_USER_ENV             = "RABBIT_MQ_DEFAULT_USER"
	RABBIT_MQ_DEFAULT_PASS_ENV             = "RABBIT_MQ_DEFAULT_PASS"
	RABBIT_MQ_DEFAULT_HOST_ENV             = "RABBIT_MQ_DEFAULT_HOST"
	RABBIT_MQ_DEFAULT_PORT_ENV             = "RABBIT_MQ_DEFAULT_PORT"
	RABBIT_MQ_DEFAULT_VHOST_ENV            = "RABBIT_MQ_DEFAULT_VHOST"
	RABBIT_MQ_CONSUMER_QUEUE_NAME_ENV      = "RABBIT_MQ_CONSUMER_QUEUE_NAME"
	RABBIT_MQ_CONSUMER_NAME_ENV            = "RABBIT_MQ_CONSUMER_NAME"
	RABBIT_MQ_NOTIFICATION_EX_ENV          = "RABBIT_MQ_NOTIFICATION_EX"
	RABBIT_MQ_NOTIFICATION_ROUTING_KEY_ENV = "RABBIT_MQ_NOTIFICATION_ROUTING_KEY"
)
